import Head from 'next/head';
import Imagem from '../components/imagem';
import Link from '../components/link';
import { Container, Footer, Main, Subtitle, Title } from '../components/style';
import styles from '../styles/Home.module.css';

export function getStaticProps() { return { props: {} }; }

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Usar como modelo */}
      {/* https://tecnoblog.net/responde/como-funciona-o-programa-de-afiliados-da-amazon/ */}

      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Subtitle>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </Subtitle>

        <Imagem src={'https://melhoreschurrasqueiras.com.br/wp-content/uploads/2021/11/Churrasqueira-a-Gas-de-embutir-Fischer-Ranch-5-Espetos-GLP-BIVOLT-1-300x195.jpg'}></Imagem>

        <Container>
          <strong>Prós</strong>
          <ul>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
            <li><a href="">Produto versátil que pode ser embutido ou usado na bancada;</a></li>
          </ul>
        </Container>

        <Container>
          <Link link={'https://amzn.to/3pDR0ng'}>Comprar com desconto</Link>
        </Container>
      </Main>

      <Footer>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </Footer>
    </Container>
  )
}
